import icon from '../favicon2.ico'
export const metadata = {
  title: 'Summer Time Bikers.js',
  description: 'Generated by Next.js',
  icons: [{ rel: 'icon', url: icon.src }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <head>
        <link rel="icon" href='../appfavicon.ico' />
      </head> */}
      <body>{children}</body>
    </html>
  )
}
