import { SectionScrollContext } from '@/components/context/SectionScrollContext'
import icon from '../favicon2.ico'
import { Analytics } from "@vercel/analytics/react"
import StickyEstimateBtn from '@/components/buttons/StickyEstimateBtn'
import StickyGformbtn from '@/components/buttons/StickyGformbtn'

export const metadata = {
  title: 'Summer Time Bikers.js',
  description: 'Generated by Next.js',
  icons: [{ rel: 'icon', url: icon.src }],
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 5,
    userScalable: true,
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log("requested");
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=yes" />
        <script src="https://kit.fontawesome.com/bfe3889fa9.js" crossOrigin="anonymous" defer></script>
      </head>
      <body>
        <SectionScrollContext>
          {children}
          <StickyEstimateBtn />
          <StickyGformbtn />
        </SectionScrollContext>
        <Analytics />
      </body>
    </html>
  )
}
