import { SectionScrollContext } from '@/components/context/SectionScrollContext'
import icon from '../favicon2.ico'
import { Analytics } from "@vercel/analytics/react"

export const metadata = {
  title: 'Summer Time Bikers.js',
  description: 'Generated by Next.js',
  icons: [{ rel: 'icon', url: icon.src }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <SectionScrollContext>
          {children}
          
        </SectionScrollContext>
      </body>
    </html>
  )
}
